(() => {
  // 中文注释：三种调制技法共享步骤骨架，保证新增酒品在调酒台内保持可执行的四步结构。
  const shakenSteps = (prep, combine, finish, time = '00:12') => [[prep, '在酒杯中加冰预冷，随后倒掉冰水。', '00:30'], ['倒入基酒', combine, ''], ['加冰摇匀', '加入冰块快速摇匀，直到摇壶外壁起雾。', time], ['滤入完成', finish, '']];
  const stirredSteps = (prep, combine, finish, time = '00:20') => [[prep, '在酒杯中加冰预冷，随后倒掉冰水。', '00:30'], ['倒入基酒', combine, ''], ['加冰搅拌', '加入冰块，以吧匙均匀搅拌至酒体冰凉。', time], ['滤入完成', finish, '']];
  const builtSteps = (prep, combine, finish, time = '00:10') => [[prep, '在杯中加入足量冰块，预先冰镇杯壁。', '00:30'], ['倒入基酒', combine, ''], ['杯中融合', '用吧匙轻轻搅拌，让风味充分融合。', time], ['完成装饰', finish, '']];

  window.marketDrinks = {
    oldFashioned: { name: '古典鸡尾酒', subtitle: '波本 · 苦精 · 橙皮', style: '威士忌', image: 'assets/rainy-neon-hero.jpg', alt: '橙皮装饰的威士忌调酒', ingredients: [['波本威士忌', '50 ml'], ['方糖', '1 块'], ['安格式苦精', '2 滴'], ['苏打水', '5 ml'], ['橙皮', '1 条']], steps: stirredSteps('准备岩石杯', '向搅拌杯加入波本、方糖、苦精与少量苏打水。', '滤入装有大冰球的岩石杯，挤橙皮香气后放入。') },
    manhattan: { name: '曼哈顿', subtitle: '黑麦 · 味美思 · 苦精', style: '威士忌', image: 'assets/rainy-neon-hero.jpg', alt: '樱桃装饰的曼哈顿调酒', ingredients: [['黑麦威士忌', '50 ml'], ['甜味美思', '20 ml'], ['安格式苦精', '2 滴'], ['樱桃', '1 颗'], ['冰块', '适量']], steps: stirredSteps('冰镇鸡尾酒杯', '向搅拌杯倒入黑麦、甜味美思和苦精。', '滤入冰镇杯中，以一颗樱桃装饰。') },
    whiskeySour: { name: '威士忌酸', subtitle: '波本 · 柠檬 · 蛋白', style: '威士忌', image: 'assets/rainy-neon-hero.jpg', alt: '柠檬装饰的威士忌酸', ingredients: [['波本威士忌', '45 ml'], ['柠檬汁', '25 ml'], ['糖浆', '20 ml'], ['蛋清', '20 ml'], ['冰块', '适量']], steps: shakenSteps('准备岩石杯', '向摇壶倒入波本、柠檬汁、糖浆和蛋清。', '滤入加冰的岩石杯，以柠檬皮装饰。') },
    martini: { name: '干马天尼', subtitle: '金酒 · 干味美思 · 橄榄', style: '金酒', image: 'assets/rainy-neon-hero.jpg', alt: '橄榄装饰的干马天尼', ingredients: [['伦敦干金酒', '60 ml'], ['干味美思', '10 ml'], ['橙味苦精', '1 滴'], ['橄榄', '2 颗'], ['冰块', '适量']], steps: stirredSteps('冰镇马天尼杯', '向搅拌杯加入金酒、干味美思和橙味苦精。', '滤入冰镇马天尼杯，串入两颗橄榄。') },
    negroni: { name: '内格罗尼', subtitle: '金酒 · 金巴利 · 味美思', style: '金酒', image: 'assets/rainy-neon-hero.jpg', alt: '橙皮装饰的内格罗尼', ingredients: [['金酒', '30 ml'], ['金巴利', '30 ml'], ['甜味美思', '30 ml'], ['橙皮', '1 条'], ['大冰球', '1 块']], steps: stirredSteps('准备岩石杯', '直接向杯中倒入金酒、金巴利和甜味美思。', '轻搅后挤橙皮香气，放入杯中。', '00:12') },
    tomCollins: { name: '汤姆柯林斯', subtitle: '金酒 · 柠檬 · 苏打', style: '金酒', image: 'assets/lime-dusk.jpg', alt: '柠檬片装饰的高球调酒', ingredients: [['金酒', '45 ml'], ['柠檬汁', '25 ml'], ['糖浆', '20 ml'], ['苏打水', '90 ml'], ['柠檬片', '1 片']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入金酒、柠檬汁和糖浆。', '补足苏打水，用柠檬片装饰。') },
    mojito: { name: '莫吉托', subtitle: '白朗姆 · 薄荷 · 青柠', style: '朗姆', image: 'assets/lime-dusk.jpg', alt: '薄荷与青柠装饰的莫吉托', ingredients: [['白朗姆', '45 ml'], ['青柠汁', '25 ml'], ['糖浆', '15 ml'], ['苏打水', '80 ml'], ['薄荷叶', '8 片']], steps: builtSteps('轻拍薄荷', '向杯中加入白朗姆、青柠汁、糖浆和薄荷叶。', '加满碎冰后补苏打水，放上薄荷顶部。') },
    daiquiri: { name: '代基里', subtitle: '白朗姆 · 青柠 · 糖浆', style: '朗姆', image: 'assets/lime-dusk.jpg', alt: '青柠风味的代基里', ingredients: [['白朗姆', '60 ml'], ['青柠汁', '25 ml'], ['糖浆', '15 ml'], ['冰块', '适量'], ['青柠皮', '1 条']], steps: shakenSteps('冰镇鸡尾酒杯', '向摇壶倒入白朗姆、青柠汁和糖浆。', '滤入冰镇杯中，放上青柠皮。') },
    cubaLibre: { name: '自由古巴', subtitle: '朗姆 · 可乐 · 青柠', style: '朗姆', image: 'assets/lime-dusk.jpg', alt: '青柠装饰的朗姆可乐', ingredients: [['深色朗姆', '50 ml'], ['可乐', '120 ml'], ['青柠汁', '15 ml'], ['冰块', '适量'], ['青柠角', '1 块']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入深色朗姆和青柠汁。', '补足可乐，用青柠角点缀。') },
    pinaColada: { name: '椰林飘香', subtitle: '朗姆 · 菠萝 · 椰奶', style: '朗姆', image: 'assets/lime-dusk.jpg', alt: '菠萝装饰的椰林飘香', ingredients: [['白朗姆', '50 ml'], ['菠萝汁', '90 ml'], ['椰奶', '40 ml'], ['糖浆', '10 ml'], ['碎冰', '适量']], steps: shakenSteps('准备飓风杯', '向摇壶倒入白朗姆、菠萝汁、椰奶与糖浆。', '连同碎冰倒入杯中，以菠萝片装饰。', '00:15') },
    maiTai: { name: '迈泰', subtitle: '陈年朗姆 · 杏仁 · 青柠', style: '朗姆', image: 'assets/party-pour.jpg', alt: '薄荷与青柠装饰的迈泰', ingredients: [['陈年朗姆', '45 ml'], ['橙味利口酒', '20 ml'], ['杏仁糖浆', '15 ml'], ['青柠汁', '25 ml'], ['薄荷叶', '4 片']], steps: shakenSteps('准备岩石杯', '向摇壶加入陈年朗姆、橙味利口酒、杏仁糖浆和青柠汁。', '滤入碎冰杯中，以薄荷和青柠皮装饰。') },
    margarita: { name: '玛格丽特', subtitle: '龙舌兰 · 橙味 · 青柠', style: '龙舌兰', image: 'assets/lime-dusk.jpg', alt: '盐边玛格丽特', ingredients: [['白龙舌兰', '50 ml'], ['橙味利口酒', '20 ml'], ['青柠汁', '25 ml'], ['海盐', '1 撮'], ['冰块', '适量']], steps: shakenSteps('准备盐边酒杯', '向摇壶倒入白龙舌兰、橙味利口酒和青柠汁。', '滤入盐边酒杯，以青柠角装饰。') },
    paloma: { name: '帕洛玛', subtitle: '龙舌兰 · 西柚 · 苏打', style: '龙舌兰', image: 'assets/lime-dusk.jpg', alt: '西柚装饰的帕洛玛', ingredients: [['白龙舌兰', '45 ml'], ['西柚汁', '75 ml'], ['青柠汁', '10 ml'], ['苏打水', '60 ml'], ['海盐', '1 撮']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入白龙舌兰、西柚汁和青柠汁。', '补入苏打水，轻撒一撮海盐。') },
    moscowMule: { name: '莫斯科骡子', subtitle: '伏特加 · 姜汁 · 青柠', style: '伏特加', image: 'assets/lime-dusk.jpg', alt: '青柠与姜汁风味的莫斯科骡子', ingredients: [['伏特加', '50 ml'], ['姜汁啤酒', '120 ml'], ['青柠汁', '15 ml'], ['冰块', '适量'], ['青柠角', '1 块']], steps: builtSteps('准备铜杯', '向加冰铜杯倒入伏特加和青柠汁。', '补姜汁啤酒，放上青柠角。') },
    bloodyMary: { name: '血腥玛丽', subtitle: '伏特加 · 番茄 · 香料', style: '伏特加', image: 'assets/party-pour.jpg', alt: '番茄风味的血腥玛丽', ingredients: [['伏特加', '45 ml'], ['番茄汁', '120 ml'], ['柠檬汁', '15 ml'], ['伍斯特酱', '3 滴'], ['黑胡椒', '1 撮']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入伏特加、番茄汁、柠檬汁和伍斯特酱。', '轻搅后撒黑胡椒，用西芹杆装饰。') },
    cosmopolitan: { name: '大都会', subtitle: '伏特加 · 蔓越莓 · 橙味', style: '伏特加', image: 'assets/rainy-neon-hero.jpg', alt: '蔓越莓风味的大都会调酒', ingredients: [['伏特加', '40 ml'], ['橙味利口酒', '20 ml'], ['蔓越莓汁', '35 ml'], ['青柠汁', '15 ml'], ['冰块', '适量']], steps: shakenSteps('冰镇马天尼杯', '向摇壶倒入伏特加、橙味利口酒、蔓越莓汁和青柠汁。', '滤入冰镇杯中，以橙皮点缀。') },
    espressoMartini: { name: '浓缩马天尼', subtitle: '伏特加 · 咖啡 · 利口酒', style: '伏特加', image: 'assets/rainy-neon-hero.jpg', alt: '咖啡豆装饰的浓缩马天尼', ingredients: [['伏特加', '45 ml'], ['咖啡利口酒', '20 ml'], ['浓缩咖啡', '30 ml'], ['糖浆', '10 ml'], ['咖啡豆', '3 颗']], steps: shakenSteps('冰镇马天尼杯', '向摇壶倒入伏特加、咖啡利口酒、浓缩咖啡和糖浆。', '滤入冰镇杯中，以三颗咖啡豆装饰。', '00:15') },
    sidecar: { name: '边车', subtitle: '白兰地 · 橙味 · 柠檬', style: '白兰地', image: 'assets/rainy-neon-hero.jpg', alt: '柠檬装饰的白兰地边车', ingredients: [['干邑白兰地', '50 ml'], ['橙味利口酒', '20 ml'], ['柠檬汁', '25 ml'], ['细砂糖', '1 撮'], ['冰块', '适量']], steps: shakenSteps('准备半糖边酒杯', '向摇壶倒入干邑、橙味利口酒和柠檬汁。', '滤入半糖边酒杯，以柠檬皮装饰。') },
    mimosa: { name: '含羞草', subtitle: '起泡酒 · 橙汁 · 柑橘', style: '起泡酒', image: 'assets/party-pour.jpg', alt: '橙汁与起泡酒的含羞草', ingredients: [['干型起泡酒', '90 ml'], ['鲜榨橙汁', '60 ml'], ['橙皮', '1 条'], ['冰块', '不需要'], ['香橙片', '1 片']], steps: builtSteps('冰镇香槟杯', '向香槟杯倒入鲜榨橙汁。', '沿杯壁缓慢补入起泡酒，以香橙片装饰。', '00:05') },
    sangria: { name: '西班牙桑格利亚', subtitle: '红葡萄酒 · 柑橘 · 水果', style: '葡萄酒', image: 'assets/party-pour.jpg', alt: '水果风味的红酒桑格利亚', ingredients: [['干红葡萄酒', '120 ml'], ['橙味利口酒', '20 ml'], ['橙汁', '30 ml'], ['苹果丁', '30 g'], ['苏打水', '40 ml']], steps: builtSteps('准备大酒杯', '向加冰酒杯倒入红葡萄酒、橙味利口酒、橙汁和苹果丁。', '轻搅后补苏打水，加入橙片。') },
    shandy: { name: '柠檬香迪', subtitle: '拉格 · 柠檬汽水 · 青柠', style: '啤酒', image: 'assets/lime-dusk.jpg', alt: '柠檬风味的啤酒香迪', ingredients: [['拉格啤酒', '150 ml'], ['柠檬汽水', '100 ml'], ['青柠汁', '10 ml'], ['冰块', '不需要'], ['青柠片', '1 片']], steps: builtSteps('冰镇啤酒杯', '向啤酒杯倒入柠檬汽水与青柠汁。', '沿杯壁补入拉格啤酒，以青柠片装饰。', '00:05') },
    baijiuLime: { name: '白酒青柠高球', subtitle: '清香白酒 · 青柠 · 苏打', style: '白酒', image: 'assets/lime-dusk.jpg', alt: '青柠与白酒风味的高球酒', ingredients: [['清香型白酒', '35 ml'], ['青柠汁', '20 ml'], ['蜂蜜糖浆', '10 ml'], ['苏打水', '100 ml'], ['青柠角', '1 块']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入白酒、青柠汁和蜂蜜糖浆。', '补足苏打水，轻搅后放上青柠角。') },
    sakeHighball: { name: '清酒高球', subtitle: '清酒 · 柚子 · 苏打', style: '清酒', image: 'assets/lime-dusk.jpg', alt: '柚子风味的清酒高球', ingredients: [['纯米清酒', '70 ml'], ['柚子汁', '15 ml'], ['糖浆', '10 ml'], ['苏打水', '80 ml'], ['柚子皮', '1 条']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入清酒、柚子汁和糖浆。', '补苏打水，以柚子皮释放香气。') },
    plumSoda: { name: '梅酒苏打', subtitle: '梅酒 · 苏打 · 紫苏', style: '梅酒', image: 'assets/lime-dusk.jpg', alt: '紫苏装饰的梅酒苏打', ingredients: [['梅酒', '60 ml'], ['苏打水', '100 ml'], ['柠檬汁', '10 ml'], ['冰块', '适量'], ['紫苏叶', '1 片']], steps: builtSteps('准备高球杯', '向加冰高球杯倒入梅酒和柠檬汁。', '补入苏打水，用紫苏叶装饰。') },
    ciderSpritz: { name: '苹果酒气泡', subtitle: '苹果酒 · 起泡酒 · 苹果', style: '苹果酒', image: 'assets/party-pour.jpg', alt: '苹果片装饰的苹果酒气泡', ingredients: [['苹果酒', '80 ml'], ['干型起泡酒', '70 ml'], ['苏打水', '30 ml'], ['苹果片', '2 片'], ['冰块', '适量']], steps: builtSteps('准备葡萄酒杯', '向加冰葡萄酒杯倒入苹果酒和干型起泡酒。', '补少量苏打水，加入两片苹果。') },
    huangjiuGinger: { name: '黄酒姜枣暖饮', subtitle: '黄酒 · 生姜 · 红枣', style: '黄酒', image: 'assets/party-pour.jpg', alt: '生姜和红枣风味的黄酒暖饮', ingredients: [['绍兴黄酒', '100 ml'], ['姜片', '3 片'], ['红枣', '2 颗'], ['冰糖', '8 g'], ['热水', '40 ml']], steps: builtSteps('温热茶杯', '向耐热杯倒入黄酒、姜片、红枣、冰糖和热水。', '隔水加热后静置片刻，温热饮用。', '01:00') }
  };
})();
